from pathlib import Path

ROOT_PATH = Path("cache")

RECV_PATH = ROOT_PATH / "recv"
SEND_PATH = ROOT_PATH / "send"
RECV_FILE_FORMAT = "md"
SEND_FILE_FORMAT = "txt"

RECV_AVATAR_PATH = RECV_PATH / "avatars"
RECV_IMAGE_PATH = RECV_PATH / "images"

RECV_GROUP_PATH = RECV_PATH / "group"
RECV_GROUP_ID_PATH = RECV_GROUP_PATH / "by_id"
RECV_GROUP_NAME_PATH = RECV_GROUP_PATH / "by_name"
RECV_GROUP_MEMO_PATH = RECV_GROUP_PATH / "by_memo"

RECV_USER_PATH = RECV_PATH / "user"
RECV_USER_ID_PATH = RECV_USER_PATH / "by_id"
RECV_USER_NAME_PATH = RECV_USER_PATH / "by_name"
RECV_USER_MEMO_PATH = RECV_USER_PATH / "by_memo"

RECV_FOCUS_PATH = RECV_PATH / "focus"
RECV_FOCUS_ID_PATH = RECV_FOCUS_PATH / "by_id"
RECV_FOCUS_NAME_PATH = RECV_FOCUS_PATH / "by_name"
RECV_FOCUS_MEMO_PATH = RECV_FOCUS_PATH / "by_memo"


SEND_GROUP_PATH = SEND_PATH / "group"
SEND_GROUP_ID_PATH = SEND_GROUP_PATH / "by_id"
SEND_GROUP_NAME_PATH = SEND_GROUP_PATH / "by_name"
SEND_GROUP_MEMO_PATH = SEND_GROUP_PATH / "by_memo"

SEND_USER_PATH = SEND_PATH / "user"
SEND_USER_ID_PATH = SEND_USER_PATH / "by_id"
SEND_USER_NAME_PATH = SEND_USER_PATH / "by_name"
SEND_USER_MEMO_PATH = SEND_USER_PATH / "by_memo"

SEND_FOCUS_PATH = SEND_PATH / "focus"
SEND_FOCUS_ID_PATH = SEND_FOCUS_PATH / "by_id"
SEND_FOCUS_NAME_PATH = SEND_FOCUS_PATH / "by_name"
SEND_FOCUS_MEMO_PATH = SEND_FOCUS_PATH / "by_memo"